spring:
  datasource:
    url: jdbc:postgresql://ep-dry-pine-aificamt-pooler.c-4.us-east-1.aws.neon.tech/neondb?currentSchema=nutri&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_PhM2pGjtlZC5
    driver-class-name: org.postgresql.Driver
